export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";

export const ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

export const NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST";
export const NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS";
export const NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET";
export const NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const USER_REVIEW_REQUEST = "USER_REVIEW_REQUEST";
export const USER_REVIEW_SUCCESS = "USER_REVIEW_SUCCESS";
export const USER_REVIEW_FAIL = "USER_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const ALL_PROCESSORS_REQUEST = "ALL_PROCESSORS_REQUEST";
export const ALL_PROCESSORS_SUCCESS = "ALL_PROCESSORS_SUCCESS";
export const ALL_PROCESSORS_FAILURE = "ALL_PROCESSORS_FAILURE";

export const ALL_GRAPHIC_CARDS_REQUEST = "ALL_GRAPHIC_CARDS_REQUEST";
export const ALL_GRAPHIC_CARDS_SUCCESS = "ALL_GRAPHIC_CARDS_SUCCESS";
export const ALL_GRAPHIC_CARDS_FAILURE = "ALL_GRAPHIC_CARDS_FAILURE";

export const COMPATIBLE_MOTHERBOARDS_REQUEST = "COMPATIBLE_MOTHERBOARDS_REQUEST";
export const COMPATIBLE_MOTHERBOARDS_SUCCESS = "COMPATIBLE_MOTHERBOARDS_SUCCESS";
export const COMPATIBLE_MOTHERBOARDS_FAILURE = "COMPATIBLE_MOTHERBOARDS_FAILURE";

export const COMPATIBLE_RAM_REQUEST = "COMPATIBLE_RAM_REQUEST";
export const COMPATIBLE_RAM_SUCCESS = "COMPATIBLE_RAM_SUCCESS";
export const COMPATIBLE_RAM_FAILURE = "COMPATIBLE_RAM_FAILURE";

export const COMPATIBLE_STORAGE_REQUEST = "COMPATIBLE_STORAGE_REQUEST";
export const COMPATIBLE_STORAGE_SUCCESS = "COMPATIBLE_STORAGE_SUCCESS";
export const COMPATIBLE_STORAGE_FAILURE = "COMPATIBLE_STORAGE_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";